# Generated by Django 5.2.1 on 2025-05-15 14:40

import django.db.models.deletion
import django.utils.timezone
import intranet_core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_descriptivo",
                    models.CharField(
                        default="",
                        help_text="Nombre descriptivo o título del archivo",
                        max_length=255,
                    ),
                ),
                (
                    "archivo_subido",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=intranet_core.models.user_directory_path,
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
