# Generated by Django 5.2.1 on 2025-05-15 15:10

import django.db.models.deletion
import django.utils.timezone
import intranet_core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intranet_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivo",
            options={},
        ),
        migrations.AddField(
            model_name="archivo",
            name="nombre_original_archivo",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="archivo",
            name="archivo_subido",
            field=models.FileField(
                default="",
                upload_to=intranet_core.models.user_directory_path,
                verbose_name="Archivo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="archivo",
            name="subido_por",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos_subidos",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Carpeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpetas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
                "unique_together": {("nombre", "subido_por")},
            },
        ),
        migrations.AddField(
            model_name="archivo",
            name="carpeta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archivos_contenidos",
                to="intranet_core.carpeta",
            ),
        ),
    ]
