# Generated by Django 5.2.1 on 2025-05-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intranet_core", "0002_alter_archivo_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticuloWiki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Dejar en blanco para autogenerar o especificar uno.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="Contenido del artículo en formato Markdown."
                    ),
                ),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
                ("actualizado_el", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articulos_wiki",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo de Wiki",
                "verbose_name_plural": "Artículos de Wiki",
                "ordering": ["-actualizado_el", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField()),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "url_destino",
                    models.URLField(
                        blank=True,
                        help_text="URL opcional a la que se dirigirá al hacer clic.",
                        null=True,
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
