# Generated by Django 5.2.1 on 2025-05-15 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intranet_core",
            "0004_recurso_tiporecurso_eventocalendario_formulario_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="carpeta",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="carpeta",
            name="carpeta_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcarpetas",
                to="intranet_core.carpeta",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carpeta",
            unique_together={("nombre", "subido_por", "carpeta_padre")},
        ),
    ]
